apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-repository-credentials
  namespace: gitops
  annotations:
    "helm.sh/hook-weight": "-10"
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: azure-keyvault-store
  target:
    name: argocd-repository-credentials
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
  data:
  - secretKey: url
    remoteRef:
      key: secret/argocd-repository-url
  - secretKey: username
    remoteRef:
      key: secret/github-credentials
      property: username
  - secretKey: password
    remoteRef:
      key: secret/github-credentials
      property: PAT