apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: {{ .Values.tektonpipelineoperator.name }}
  name: {{ .Values.tektonpipelineoperator.name }}
  namespace: {{ .Release.Namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      control-plane: {{ .Values.tektonpipelineoperator.name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        control-plane: {{ .Values.tektonpipelineoperator.name }}
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
        imagePullPolicy: Always
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - args:
        - --health-probe-bind-address=:6789
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        - --leader-election-id=tektonpipelineoperator
        env:
        - name: ANSIBLE_GATHERING
          value: explicit
        {{- range $envFromSecret := .Values.tektonpipelineoperator.envFromSecret }}
        - name: {{ $envFromSecret.name }}
          valueFrom:
            secretKeyRef:
              name: {{ $envFromSecret.valueFrom.secretKeyRef.name }}
              key: {{ $envFromSecret.valueFrom.secretKeyRef.key }}
        {{- end }}
        image: {{.Values.tektonpipelineoperator.image.registry }}/{{ .Values.tektonpipelineoperator.image.name }}:{{ .Values.tektonpipelineoperator.image.tag }}
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 6789
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        name: manager
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: 6789
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/ansible/.ansible/tmp
          name: tmp
      volumes:
      - name: tmp
        emptyDir: {}
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: "github"
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      serviceAccount: {{ .Values.tektonpipelineoperator.name }}-controller-manager
      serviceAccountName: {{ .Values.tektonpipelineoperator.name }}-controller-manager
      terminationGracePeriodSeconds: 10
