apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: {{ .Values.tektonpipelineoperator.name }}
  name: {{ .Values.tektonpipelineoperator.name }}-svc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: {{ .Values.tektonpipelineoperator.name }}
