githubteamuseroperator:
  name: githubteamuseroperator
  image:
    registry: ghcr.io/knot-test-organization
    name: knot-githubteamuseroperator
    tag: 12
  envFromSecret:
    - name: GITHUB_USERNAME
      valueFrom:
        secretKeyRef:
          name: github-credentials
          key: username
    - name: PAT
      valueFrom:
        secretKeyRef:
          name: github-credentials
          key: PAT