apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-keyvault-store
  namespace: gitops
spec:
  provider:
    azurekv:
      tenantId: "d55edb3e-09c5-417c-b1ee-d6f248126461"
      vaultUrl: "https://github-knot-kv.vault.azure.net/"
      authSecretRef:
        clientId:
          name: azure-login
          key: AZURE_CLIENT_ID
        clientSecret:
          name: azure-login
          key: AZURE_SECRET