githubteamoperator:
  name: githubteamoperator
  image:
    registry: ghcr.io/knot-test-organization
    name: knot-githubteamoperator
    tag: 22
  envFromSecret:
    - name: GITHUB_USERNAME
      valueFrom:
        secretKeyRef:
          name: github-credentials
          key: username
    - name: PAT
      valueFrom:
        secretKeyRef:
          name: github-credentials
          key: PAT