tektonpipelineoperator:
  name: tektonpipelineoperator
  image:
    registry: ghcr.io/knot-test-organization
    name: knot-tektonpipelineoperator
    tag: 58
  envFromSecret:
    - name: GITHUB_USERNAME
      valueFrom:
        secretKeyRef:
          name: github-credentials
          key: username
    - name: PAT
      valueFrom:
        secretKeyRef:
          name: github-credentials
          key: PAT