apiVersion: v1
kind: Secret
metadata:
  name: azure-login
  namespace: gitops
type: Opaque
data:
  AZURE_CLIENT_ID: YTU0YzBmMWItYWIxMC00OThjLTk0NjUtNjU0YTdjZGJiM2Jj
  AZURE_SECRET: YzdXOFF+TnBJTzR3aFNqX1hSZTl+YWg3dUFfbTEwQkw5OGxobWFrNQ==
  AZURE_SUBSCRIPTION_ID: Njc0Mjc5ZDctYTI5MS00NTZjLThkZDMtMDNiMjBlMTAwY2Q1
  AZURE_TENANT: ZDU1ZWRiM2UtMDljNS00MTdjLWIxZWUtZDZmMjQ4MTI2NDYx
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-login
  namespace: tekton-pipelines
type: Opaque
data:
  AZURE_CLIENT_ID: YTU0YzBmMWItYWIxMC00OThjLTk0NjUtNjU0YTdjZGJiM2Jj
  AZURE_SECRET: YzdXOFF+TnBJTzR3aFNqX1hSZTl+YWg3dUFfbTEwQkw5OGxobWFrNQ==
  AZURE_SUBSCRIPTION_ID: Njc0Mjc5ZDctYTI5MS00NTZjLThkZDMtMDNiMjBlMTAwY2Q1
  AZURE_TENANT: ZDU1ZWRiM2UtMDljNS00MTdjLWIxZWUtZDZmMjQ4MTI2NDYx
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-login
  namespace: flux-system
type: Opaque
data:
  AZURE_CLIENT_ID: YTU0YzBmMWItYWIxMC00OThjLTk0NjUtNjU0YTdjZGJiM2Jj
  AZURE_SECRET: YzdXOFF+TnBJTzR3aFNqX1hSZTl+YWg3dUFfbTEwQkw5OGxobWFrNQ==
  AZURE_SUBSCRIPTION_ID: Njc0Mjc5ZDctYTI5MS00NTZjLThkZDMtMDNiMjBlMTAwY2Q1
  AZURE_TENANT: ZDU1ZWRiM2UtMDljNS00MTdjLWIxZWUtZDZmMjQ4MTI2NDYx
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-login
  namespace: external-secrets
type: Opaque
data:
  AZURE_CLIENT_ID: YTU0YzBmMWItYWIxMC00OThjLTk0NjUtNjU0YTdjZGJiM2Jj
  AZURE_SECRET: YzdXOFF+TnBJTzR3aFNqX1hSZTl+YWg3dUFfbTEwQkw5OGxobWFrNQ==
  AZURE_SUBSCRIPTION_ID: Njc0Mjc5ZDctYTI5MS00NTZjLThkZDMtMDNiMjBlMTAwY2Q1
  AZURE_TENANT: ZDU1ZWRiM2UtMDljNS00MTdjLWIxZWUtZDZmMjQ4MTI2NDYx