apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: generic-app-off-appsets
  namespace: {{ .Release.Namespace }}
spec:
  destination:
    namespace: {{ .Release.Namespace }}
    server: https://kubernetes.default.svc
  project: default
  source:
    path: generic-application-sets
    repoURL: https://github.com/everis-technology/hybrid-automation.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true