apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: basic-user-pass
  namespace: gitops
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: azure-keyvault-store
  target:
    name: basic-user-pass
    creationPolicy: Owner
    template:
      metadata:
        annotations:
          tekton.dev/git-0: https://github.com
      type: kubernetes.io/basic-auth
  data:
  - secretKey: username
    remoteRef:
      key: secret/basic-user-pass
      property: username
  - secretKey: password
    remoteRef:
      key: secret/basic-user-pass
      property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: basic-user-pass
  namespace: tekton-pipelines
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: azure-keyvault-store
  target:
    name: basic-user-pass
    creationPolicy: Owner
    template:
      metadata:
        annotations:
          tekton.dev/git-0: https://github.com
      type: kubernetes.io/basic-auth
  data:
  - secretKey: username
    remoteRef:
      key: secret/basic-user-pass
      property: username
  - secretKey: password
    remoteRef:
      key: secret/basic-user-pass
      property: password