apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: flux-system
  namespace: flux-system
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: azure-keyvault-store
  target:
    name: flux-system
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: secret/github-credentials
      property: username
  - secretKey: password
    remoteRef:
      key: secret/github-credentials
      property: PAT