apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: git-basic-auth-secret
  namespace: flux-system
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: azure-keyvault-store
  target:
    creationPolicy: Owner
    name: git-basic-auth-secret
  data:
  - remoteRef:
      key: secret/git-basic-auth-secret
      property: .git-credentials
    secretKey: .git-credentials
  - remoteRef:
      key: secret/git-basic-auth-secret
      property: .gitconfig
    secretKey: .gitconfig
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: git-basic-auth-secret
  namespace: gitops
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: azure-keyvault-store
  target:
    creationPolicy: Owner
    name: git-basic-auth-secret
  data:
  - remoteRef:
      key: secret/git-basic-auth-secret
      property: .git-credentials
    secretKey: .git-credentials
  - remoteRef:
      key: secret/git-basic-auth-secret
      property: .gitconfig
    secretKey: .gitconfig
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: git-basic-auth-secret
  namespace: tekton-pipelines
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: azure-keyvault-store
  target:
    creationPolicy: Owner
    name: git-basic-auth-secret
  data:
  - remoteRef:
      key: secret/git-basic-auth-secret
      property: .git-credentials
    secretKey: .git-credentials
  - remoteRef:
      key: secret/git-basic-auth-secret
      property: .gitconfig
    secretKey: .gitconfig