apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github
  namespace: gitops
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: azure-keyvault-store
  target:
    name: github
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
  data:
  - secretKey: .dockerconfigjson
    remoteRef:
      key: secret/github
      property: .dockerconfigjson