apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-credentials
  namespace: gitops
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: azure-keyvault-store
  target:
    name: github-credentials
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: secret/github-credentials
      property: username
  - secretKey: PAT
    remoteRef:
      key: secret/github-credentials
      property: PAT