apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: microsoft-graph-token
  namespace: gitops
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: azure-keyvault-store
  target:
    name: microsoft-graph-token
    creationPolicy: Owner
  data:
  - secretKey: microsoft-graph-token
    remoteRef:
      key: secret/microsoft-graph-token