apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonar-token-auth-secret
  namespace: tekton-pipelines
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: azure-keyvault-store
  target:
    name: sonar-token-auth-secret
    creationPolicy: Owner
  data:
  - secretKey: login
    remoteRef:
      key: secret/sonar-token-auth-secret