apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: webhook-secret
  namespace: tekton-pipelines
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: azure-keyvault-store
  target:
    name: webhook-secret
    creationPolicy: Owner
  data:
  - secretKey: secret
    remoteRef:
      key: secret/webhook-secret
      property: secret
  - secretKey: token
    remoteRef:
      key: secret/webhook-secret
      property: token