apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: gitops
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: {{ .Values.frontend.image.registry }}/{{ .Values.frontend.image.name }}:{{ .Values.frontend.image.tag }}
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: "github"