githubcodespaceoperator:
  name: github-codespaceoperator
  image:
    registry: ghcr.io/knot-test-organization
    name: knot-github-codespaceoperator
    tag: 70
  envFromSecret:
    - name: GITHUB_USERNAME
      valueFrom:
        secretKeyRef:
          name: github-credentials
          key: username
    - name: PAT
      valueFrom:
        secretKeyRef:
          name: github-credentials
          key: PAT