apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.knot_code_api.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.knot_code_api.name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080